/**
 * Decision Entity
 *
 * Represents an architectural decision with ADR-level detail.
 * This is a specialized memory type for the Architectural memory category.
 */

import type {
  MemoryId,
  ProjectId,
  Timestamp,
} from '../types.js';

/**
 * An alternative that was considered during decision-making.
 */
export interface Alternative {
  readonly name: string;
  readonly description: string;
  readonly rejected: boolean;
  readonly reason?: string;
}

/**
 * A consequence of a decision (positive or negative).
 */
export interface Consequence {
  readonly type: 'positive' | 'negative' | 'neutral';
  readonly description: string;
}

/**
 * Decision entity — architectural decisions with full context.
 */
export interface Decision {
  readonly id: MemoryId;
  readonly decision: string;
  readonly context: string;
  readonly alternativesConsidered: readonly Alternative[];
  readonly consequences: readonly Consequence[];
  readonly project?: ProjectId;
  readonly createdAt: Timestamp;
  readonly decidedBy?: string;
}

/**
 * Input for recording a new decision
 */
export interface RecordDecisionInput {
  decision: string;
  context: string;
  alternativesConsidered: Alternative[];
  consequences: Consequence[];
  project?: ProjectId;
  decidedBy?: string;
}

/**
 * Create a new Decision entity.
 *
 * @param id - Unique identifier (generated by caller)
 * @param input - Decision recording parameters
 * @returns New Decision instance
 */
export function recordDecision(id: MemoryId, input: RecordDecisionInput): Decision {
  return {
    id,
    decision: input.decision,
    context: input.context,
    alternativesConsidered: Object.freeze(input.alternativesConsidered),
    consequences: Object.freeze(input.consequences),
    project: input.project,
    createdAt: new Date().toISOString(),
    decidedBy: input.decidedBy,
  };
}
