/**
 * Memory Entity
 *
 * Core domain entity representing a single memory unit.
 * Immutable value object with factory methods.
 */

import type {
  MemoryId,
  MemoryType,
  StorageTier,
  ProjectId,
  Timestamp,
  Embedding,
  Weight,
  DecayRate,
} from '../types.js';
import { DECAY_RATES, DEFAULT_TIERS, REINFORCEMENT_BOOSTS } from '../types.js';

/**
 * Memory entity — the atomic unit of Chronicle storage.
 *
 * Memories are immutable. All mutations return new Memory instances.
 */
export interface Memory {
  readonly id: MemoryId;
  readonly content: string;
  readonly memoryType: MemoryType;
  readonly tier: StorageTier;
  readonly weight: Weight;
  readonly decayRate: DecayRate;
  readonly accessCount: number;
  readonly createdAt: Timestamp;
  readonly lastAccessedAt: Timestamp;
  readonly project?: ProjectId;
  readonly category?: string;
  readonly tags: readonly string[];
  readonly source?: string;
  readonly embedding?: Embedding;
  readonly confirmed: boolean;
}

/**
 * Input for creating a new memory
 */
export interface CreateMemoryInput {
  content: string;
  memoryType: MemoryType;
  project?: ProjectId;
  category?: string;
  tags?: string[];
  source?: string;
  confidence?: number;
  confirmed?: boolean;
}

/**
 * Create a new Memory entity with computed defaults.
 *
 * @param id - Unique identifier (generated by caller)
 * @param input - Memory creation parameters
 * @returns New Memory instance
 */
export function createMemory(id: MemoryId, input: CreateMemoryInput): Memory {
  const now = new Date().toISOString();
  const memoryType = input.memoryType;

  // Confirmed memories get immediate boost
  const baseWeight = 0.5;
  const confirmedBoost = input.confirmed ? REINFORCEMENT_BOOSTS.CONFIRMED_REMEMBER : 0;
  const initialWeight = Math.min(1.0, baseWeight + confirmedBoost);

  return {
    id,
    content: input.content,
    memoryType,
    tier: DEFAULT_TIERS[memoryType],
    weight: initialWeight,
    decayRate: DECAY_RATES[memoryType],
    accessCount: 0,
    createdAt: now,
    lastAccessedAt: now,
    project: input.project,
    category: input.category,
    tags: Object.freeze(input.tags ?? []),
    source: input.source,
    embedding: undefined, // Computed asynchronously by infrastructure
    confirmed: input.confirmed ?? false,
  };
}

/**
 * Apply reinforcement boost to memory weight.
 *
 * Formula: weight += boost × (1 - weight)
 * This ensures weight asymptotically approaches 1.0.
 *
 * @param memory - Memory to reinforce
 * @param boost - Boost value from REINFORCEMENT_BOOSTS
 * @returns New Memory with updated weight and access metadata
 */
export function reinforceMemory(memory: Memory, boost: number): Memory {
  const newWeight = Math.min(1.0, memory.weight + boost * (1 - memory.weight));
  return {
    ...memory,
    weight: newWeight,
    accessCount: memory.accessCount + 1,
    lastAccessedAt: new Date().toISOString(),
  };
}

/**
 * Apply decay to memory weight.
 *
 * Formula: weight *= e^(-decayRate × daysSinceLastAccess)
 *
 * @param memory - Memory to decay
 * @param daysSinceLastAccess - Days since last access
 * @returns New Memory with decayed weight
 */
export function decayMemory(memory: Memory, daysSinceLastAccess: number): Memory {
  if (memory.decayRate === 0) {
    return memory; // No decay for procedural/architectural
  }
  const decayFactor = Math.exp(-memory.decayRate * daysSinceLastAccess);
  return {
    ...memory,
    weight: memory.weight * decayFactor,
  };
}

/**
 * Promote memory to a higher storage tier.
 *
 * @param memory - Memory to promote
 * @param newTier - Target tier
 * @returns New Memory with updated tier
 */
export function promoteMemory(memory: Memory, newTier: StorageTier): Memory {
  return {
    ...memory,
    tier: newTier,
  };
}

/**
 * Attach embedding vector to memory.
 *
 * @param memory - Memory to update
 * @param embedding - Vector embedding
 * @returns New Memory with embedding
 */
export function attachEmbedding(memory: Memory, embedding: Embedding): Memory {
  return {
    ...memory,
    embedding,
  };
}
