/**
 * Preference Entity
 *
 * Represents a developer preference (coding style, tooling, etc.)
 */

import type {
  MemoryId,
  ProjectId,
  Timestamp,
} from '../types.js';

/** Preference strength: how strongly the developer holds this preference */
export type PreferenceStrength = 'strong' | 'moderate' | 'weak';

/**
 * Preference entity — developer preferences and settings.
 */
export interface Preference {
  readonly id: MemoryId;
  readonly key: string;
  readonly value: string;
  readonly context?: string;
  readonly strength: PreferenceStrength;
  readonly project?: ProjectId;
  readonly createdAt: Timestamp;
  readonly updatedAt: Timestamp;
}

/**
 * Input for setting a new preference
 */
export interface SetPreferenceInput {
  key: string;
  value: string;
  context?: string;
  strength?: PreferenceStrength;
  project?: ProjectId;
}

/**
 * Create a new Preference entity.
 *
 * @param id - Unique identifier (generated by caller)
 * @param input - Preference set parameters
 * @returns New Preference instance
 */
export function setPreference(id: MemoryId, input: SetPreferenceInput): Preference {
  const now = new Date().toISOString();
  return {
    id,
    key: input.key,
    value: input.value,
    context: input.context,
    strength: input.strength ?? 'moderate',
    project: input.project,
    createdAt: now,
    updatedAt: now,
  };
}

/**
 * Update an existing preference.
 *
 * @param preference - Preference to update
 * @param updates - New value and/or strength
 * @returns New Preference with updates
 */
export function updatePreference(
  preference: Preference,
  updates: { value?: string; strength?: PreferenceStrength }
): Preference {
  return {
    ...preference,
    value: updates.value ?? preference.value,
    strength: updates.strength ?? preference.strength,
    updatedAt: new Date().toISOString(),
  };
}
