/**
 * PromptLog entity.
 *
 * Represents an opted-in prompt pattern record.
 * Raw content is only stored when the user explicitly sets shareContent: true.
 */

export type PromptOutcome = 'good' | 'bad' | 'neutral';

export type PromptCategory =
  | 'debugging'
  | 'refactoring'
  | 'architecture'
  | 'testing'
  | 'docs'
  | 'review'
  | 'generation'
  | 'general';

export type PromptLogStatus = 'pending' | 'pushed';

/** A locally buffered prompt pattern log */
export interface PromptLog {
  readonly id: string;
  readonly userId: string;
  readonly teamId: string;
  readonly project?: string;
  /** What the prompt was trying to achieve — not the raw prompt */
  readonly pattern: string;
  readonly outcome: PromptOutcome;
  readonly category: PromptCategory | string;
  readonly tags: readonly string[];
  /** When true, raw content is shared; user must opt in explicitly */
  readonly shareContent: boolean;
  readonly rawContent?: string;
  readonly loggedAt: string;
  readonly status: PromptLogStatus;
}

export interface CreatePromptLogInput {
  userId: string;
  teamId: string;
  project?: string;
  pattern: string;
  outcome?: PromptOutcome;
  category?: PromptCategory | string;
  tags?: string[];
  shareContent?: boolean;
  rawContent?: string;
}

/**
 * Create a new PromptLog entity.
 *
 * @param id - Unique identifier (generated by caller)
 * @param input - Log creation parameters
 * @returns New PromptLog entity with status 'pending'
 */
export function createPromptLog(id: string, input: CreatePromptLogInput): PromptLog {
  return {
    id,
    userId: input.userId,
    teamId: input.teamId,
    project: input.project,
    pattern: input.pattern,
    outcome: input.outcome ?? 'neutral',
    category: input.category ?? 'general',
    tags: Object.freeze(input.tags ?? []),
    shareContent: input.shareContent ?? false,
    rawContent: input.shareContent ? input.rawContent : undefined,
    loggedAt: new Date().toISOString(),
    status: 'pending',
  };
}
