/**
 * Session Entity
 *
 * Represents a developer work session for continuity and recovery.
 */

import type {
  SessionId,
  ProjectId,
  Timestamp,
} from '../types.js';

/** Session status */
export type SessionStatus = 'active' | 'ended' | 'crashed';

/**
 * Session entity — tracks live context of a work session.
 */
export interface Session {
  readonly id: SessionId;
  readonly project: ProjectId;
  readonly device?: string;
  readonly status: SessionStatus;
  readonly startedAt: Timestamp;
  readonly endedAt?: Timestamp;
  readonly activeTasks: readonly string[];
  readonly pendingDecisions: readonly string[];
  readonly touchedFiles: readonly string[];
  readonly summary?: string;
}

/**
 * Input for starting a new session
 */
export interface StartSessionInput {
  project: ProjectId;
  device?: string;
}

/**
 * Create a new Session entity.
 *
 * @param id - Unique identifier (generated by caller)
 * @param input - Session start parameters
 * @returns New Session instance
 */
export function startSession(id: SessionId, input: StartSessionInput): Session {
  return {
    id,
    project: input.project,
    device: input.device,
    status: 'active',
    startedAt: new Date().toISOString(),
    endedAt: undefined,
    activeTasks: [],
    pendingDecisions: [],
    touchedFiles: [],
    summary: undefined,
  };
}

/**
 * End a session normally.
 *
 * @param session - Session to end
 * @param summary - Optional session summary
 * @returns New Session with ended status
 */
export function endSession(session: Session, summary?: string): Session {
  return {
    ...session,
    status: 'ended',
    endedAt: new Date().toISOString(),
    summary,
  };
}

/**
 * Mark a session as crashed (for recovery).
 *
 * @param session - Session that crashed
 * @returns New Session with crashed status
 */
export function markSessionCrashed(session: Session): Session {
  return {
    ...session,
    status: 'crashed',
    endedAt: new Date().toISOString(),
  };
}

/**
 * Update session with active context.
 *
 * @param session - Session to update
 * @param updates - Partial updates to apply
 * @returns New Session with updates
 */
export function updateSessionContext(
  session: Session,
  updates: {
    activeTasks?: readonly string[];
    pendingDecisions?: readonly string[];
    touchedFiles?: readonly string[];
  }
): Session {
  return {
    ...session,
    activeTasks: updates.activeTasks ?? session.activeTasks,
    pendingDecisions: updates.pendingDecisions ?? session.pendingDecisions,
    touchedFiles: updates.touchedFiles ?? session.touchedFiles,
  };
}
