/**
 * Solution Entity
 *
 * Represents a reusable solution in the cross-project solution library.
 * This is a specialized memory type for the Procedural memory category.
 */

import type {
  MemoryId,
  ProjectId,
  Timestamp,
  Embedding,
} from '../types.js';

/**
 * Solution entity — a reusable problem-solution pair.
 */
export interface Solution {
  readonly id: MemoryId;
  readonly problem: string;
  readonly solution: string;
  readonly language?: string;
  readonly tags: readonly string[];
  readonly sourceProject?: ProjectId;
  readonly sourceFile?: string;
  readonly createdAt: Timestamp;
  readonly embedding?: Embedding;
}

/**
 * Input for saving a new solution
 */
export interface SaveSolutionInput {
  problem: string;
  solution: string;
  language?: string;
  tags?: string[];
  sourceProject?: ProjectId;
  sourceFile?: string;
}

/**
 * Create a new Solution entity.
 *
 * @param id - Unique identifier (generated by caller)
 * @param input - Solution save parameters
 * @returns New Solution instance
 */
export function saveSolution(id: MemoryId, input: SaveSolutionInput): Solution {
  return {
    id,
    problem: input.problem,
    solution: input.solution,
    language: input.language,
    tags: Object.freeze(input.tags ?? []),
    sourceProject: input.sourceProject,
    sourceFile: input.sourceFile,
    createdAt: new Date().toISOString(),
    embedding: undefined,
  };
}

/**
 * Attach embedding vector to solution for semantic search.
 *
 * @param solution - Solution to update
 * @param embedding - Vector embedding
 * @returns New Solution with embedding
 */
export function attachSolutionEmbedding(solution: Solution, embedding: Embedding): Solution {
  return {
    ...solution,
    embedding,
  };
}
