/**
 * Trigger Entity
 *
 * Represents a trigger attached to a memory that fires before risky actions.
 */

import type {
  TriggerId,
  MemoryId,
  TriggerAction,
  TriggerSeverity,
  Timestamp,
} from '../types.js';

/**
 * Trigger entity — links a memory to an action that should surface it.
 */
export interface Trigger {
  readonly id: TriggerId;
  readonly memoryId: MemoryId;
  readonly action: TriggerAction;
  readonly severity: TriggerSeverity;
  readonly createdAt: Timestamp;
  readonly active: boolean;
}

/**
 * Input for creating a new trigger
 */
export interface CreateTriggerInput {
  memoryId: MemoryId;
  action: TriggerAction;
  severity: TriggerSeverity;
}

/**
 * Create a new Trigger entity.
 *
 * @param id - Unique identifier (generated by caller)
 * @param input - Trigger creation parameters
 * @returns New Trigger instance
 */
export function createTrigger(id: TriggerId, input: CreateTriggerInput): Trigger {
  return {
    id,
    memoryId: input.memoryId,
    action: input.action,
    severity: input.severity,
    createdAt: new Date().toISOString(),
    active: true,
  };
}

/**
 * Deactivate a trigger.
 *
 * @param trigger - Trigger to deactivate
 * @returns New Trigger with active=false
 */
export function deactivateTrigger(trigger: Trigger): Trigger {
  return {
    ...trigger,
    active: false,
  };
}
